services:

  jenkins:
    image: jljl1337/jenkins-docker:2.504.3-lts-slim
    container_name: homelab-jenkins
    restart: unless-stopped
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.${DOMAIN_NAME}`)"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"


  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:0.3.0
    container_name: homelab-docker-socket-proxy
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - POST=1
      - CONTAINERS=1
      - EXEC=1
      - IMAGES=1
      - SERVICES=1
      - TASKS=1
      - NETWORKS=1
      - NODES=1

volumes:
  jenkins-data: