services:

  makemkv:
    image: jlesage/makemkv:v25.07.1
    container_name: homelab-makemkv
    restart: unless-stopped
    devices:
      - ${MAKEMKV_DEVICE_SR}
      - ${MAKEMKV_DEVICE_SG}
    volumes:
      - ${MAKEMKV_OUTPUT}:/output
      - makemkv_config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.makemkv.rule=Host(`makemkv.${DOMAIN_NAME}`)"
      - "traefik.http.routers.makemkv.entrypoints=websecure"
      - "traefik.http.services.makemkv.loadbalancer.server.port=5800"


volumes:
  makemkv_config: