services:

  scrutiny:
    image: ghcr.io/analogj/scrutiny:v0.8.1-omnibus
    container_name: homelab-scrutiny
    cap_add:
      - SYS_RAWIO
    volumes:
      - /run/udev:/run/udev:ro
      - scrutiny_config:/opt/scrutiny/config
      - scrutiny_influxdb:/opt/scrutiny/influxdb
    devices:
      # Add more devices if you have more than 2 hard drives
      - ${SCRUTINY_DEVICE_01}
      - ${SCRUTINY_DEVICE_02}
    environment:
      - TZ=${TZ}
      - "COLLECTOR_CRON_SCHEDULE=30 4 * * *"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scrutiny.rule=Host(`scrutiny.${DOMAIN_NAME}`)"
      - "traefik.http.routers.scrutiny.entrypoints=websecure"
      - "traefik.http.services.scrutiny.loadbalancer.server.port=8080"


volumes:
  scrutiny_config:
  scrutiny_influxdb: