services:

  komodo-mongo:
    image: mongo:8.0.11
    container_name: homelab-komodo-mongo
    restart: unless-stopped
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    command: --quiet --wiredTigerCacheSizeGB 0.25
    volumes:
      - komodo-mongo-data:/data/db
      - komodo-mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  komodo-core:
    image: ghcr.io/moghtech/komodo-core:1.18.4
    container_name: homelab-komodo-core
    # labels:
    #   komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    depends_on:
      - komodo-mongo
    logging:
      driver: local
    environment:
      KOMODO_DATABASE_ADDRESS: komodo-mongo:27017
      KOMODO_DATABASE_USERNAME: admin
      KOMODO_DATABASE_PASSWORD: admin
      KOMODO_FIRST_SERVER: https://komodo-periphery:8120
      KOMODO_LOCAL_AUTH: "true"
    volumes:
      - komodo-repo-cache:/repo-cache
    labels:
      - "komodo.skip" # Prevent Komodo from stopping with StopAllContainers

      - "traefik.enable=true"
      - "traefik.http.routers.komodo.rule=Host(`komodo.${DOMAIN_NAME}`)"
      - "traefik.http.routers.komodo.entrypoints=websecure"
      - "traefik.http.services.komodo.loadbalancer.server.port=9120"


  komodo-periphery:
    image: ghcr.io/moghtech/komodo-periphery:1.18.4
    container_name: homelab-komodo-periphery
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    logging:
      driver: local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /etc/komodo:/etc/komodo

volumes:
  komodo-mongo-data:
  komodo-mongo-config:
  komodo-repo-cache: