services:

  mkvtoolnix:
    image: jlesage/mkvtoolnix:v25.07.1
    container_name: homelab-mkvtoolnix
    restart: unless-stopped
    volumes:
      - mkvtoolnix_config:/config
      - ${MKVTOOLNIX_STORAGE}:/storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mkvtoolnix.rule=Host(`mkvtoolnix.${DOMAIN_NAME}`)"
      - "traefik.http.routers.mkvtoolnix.entrypoints=websecure"
      - "traefik.http.services.mkvtoolnix.loadbalancer.server.port=5800"


volumes:
  mkvtoolnix_config: